server:
  port: 8082
  servlet:
    contextPath: /cyberware
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cyberware?user=root&password=password
    driverClassName: org.mariadb.jdbc.Driver